### PR TITLE
Hotfix/fix build actions

### PR DESCRIPTION
**Pull request by TrevorPayne**
Updates the build actions to reflect know working build actions.

Updates AssemblyInfo copyright for proper year

Updates nuspec file for proper year.

### CODE REVIEW

**Review by jtalborough — APPROVED** [review]

**Review by jtalborough — APPROVED** [review]

**Review by jtalborough — CHANGES_REQUESTED** [review]
I'm thinking we should name this file .nuspecTEMPLATE or something to make it non-functional. This file will require editing and the specifics of the consumer.

**Comment by TrevorPayne** [comment]
That makes sense - especially since the workflows no longer require us to explicitly edit them to work.

As I learn more about this, I want to find more ways to make this sort of data dynamic, but I'm currently not sure if it is possible.  I feel like our gh actions should be able to generate the nuspec file based on parameters set in the solution, but I don't really know.  Maybe it's a pipe(line - heh) dream

Trevor Payne, CTS, CCMP-Silver
Software Engineer
PepperDash
www.pepperdash.com
617.206.9807



PepperDash Mobile Control™ - BYOD Crestron Control, no special app required


On Jul 15, 2022 7:27 AM, Jason T Alborough ***@***.***> wrote:

@jtalborough requested changes on this pull request.

I'm thinking we should name this file .nuspecTEMPLATE or something to make it non-functional. This file will require editing and the specifics of the consumer.

**Comment by jtalborough** [comment]
> I feel like our gh actions should be able to generate the nuspec file based on parameters set in the solution, but I don't really know. 

I think you are correct. The workflow should have all the necessary info and we can build a nuspec with powershell. For now ill add -TEMPLATE to the nuspec and some brief instructions in the readme.

**Comment by TrevorPayne** [comment]
Found a couple articles on how to do it - I may test it out today.

Anything to limit the number of "changes" that have to be manually made to the template to get a properly functioning workflow is a good thing in my book.

I would really love to have a PowerShell script that properly changes the solution name and such without manual adjustment as well, but that's beyond the scope of this specific PR.

Trevor Payne, CTS, CCMP-Silver
Software Engineer
PepperDash
www.pepperdash.com
617.206.9807



PepperDash Mobile Control™ - BYOD Crestron Control, no special app required


On Jul 15, 2022 7:36 AM, Jason T Alborough ***@***.***> wrote:

I feel like our gh actions should be able to generate the nuspec file based on parameters set in the solution, but I don't really know.

I think you are correct. The workflow should have all the necessary info and we can build a nuspec with powershell. For now ill add -TEMPLATE to the nuspec and some brief instructions in the readme.

**Pull request closed without merging**
